use_frameworks!

platform :ios, '9.0'

target 'LLUNetworking_Example' do
  pod 'LLUNetworking', :path => '../'

  target 'LLUNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
